# docker-compose.yml
version: '3.8'

services:
  discord-bot:
    build: .
    volumes:
      - ./google_credentials.json:/app/google_credentials.json:ro
      - ./config.json:/app/config.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google_credentials.json
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
